### ISSUE TITLE
Method for running locally

### ISSUE THREAD

**Issue by klei22** [AlexW00/Flow_Graph#1]
What would the recommended way be to run locally without publishing in gh-pages?

**Comment by AlexW00** [comment]
In your terminal:

1. (install [Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) and [NodeJS](https://nodejs.org/en/))
2. clone the repo via `git clone https://github.com/AlexW00/Flow_Graph`
3. run `cd ./Flow_Graph` to navigate into the directory
4. run `npm run dev` to start the server
